language: python
python:
  - "3.8"

sudo: required

services:
  - docker

before_script:
  - pip install docker-compose
  - sudo chmod -R 777 .

script:
  - docker-compose run --rm todoapi sh -c "python3 manage.py test"